### ISSUE TITLE
Custom MAVLink Messages

### ISSUE THREAD

**Issue by fhgrderungs** [asvol/asv-mavlink#1]
First of all, thank you very much for this library! Very well done.

I managed to read and write MAVLink messages. Next up would be to implement custom messages. For this, I cloned this repo, compiled it and ran 

`Asv.Mavlink.Shell.exe gen -t=mydialect.xml -i=messages -o=src/Asv.Mavlink/Connection/Dialects -e=cs csharp.tpl`

then I have mydialect.cs which I can include in my project and call `RegisterMyDialectDialect`.

Unfortunately the mydialect.cs references Asv.Tools (for BinSerialize) which doesn't seem to exist as NuGet package.

Are there any plans on publishing the Asv.Tools lib? I don't really want to clone and integrate Asv.Tools repo. Instead, a separate NuGet would be optimal.

**Comment by asvol** [comment]
Sorry for long answer. Asv.Tools changed to Asv.IO. You can find it in nugget. You can sent me a file with custom Mavlink messages, I'll check it.

**Comment by fhgrderungs** [comment]
Thank you. Would it be possible to udpate `csharp.tpl` so that it references `using Asv.IO;` instead of `using Asv.Tools;`? I can make a pull request if you're ok with that. I would like to not manually change said lines after generating the code.

By the way: What's the difference between https://github.com/asvol/asv-mavlink and https://github.com/asvol/mavlink.net?

**Comment by asvol** [comment]
Thx for pull request. Approved it. About the difference: mavlink.net was an internal project with git-submodule dependencies for a graphical application. I didn't think about using it as a public nuget package. Right now I'm refactoring all my libraries to open source with nuget usages. In order not to break the dependencies, I decided to create a new project, divided the payload and the main library for working with UAVs. Maybe soon I will publish a graphical application for Avalonia on all platforms like MissionPlanner or QGroundControl. 

Summaries: asv-mavlink continuation of mavlink.net after hard refactoring.
